# Generated by Django 5.2.7 on 2025-11-14 12:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_song_count_song_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='song',
            name='count',
            field=models.IntegerField(default=0),
        ),
    ]
